### ISSUE TITLE
Weird behaviour for video on scroll

### ISSUE THREAD

**Issue by Kitlabs** [eneim/toro#383]
please check this recording
this is really unexpected behavior.

mtp://[usb:001,033]/Internal%20shared%20storage/AzRecorderFree/2018_09_19_19_13_12.mp4

**Comment by Kitlabs** [comment]
@eneim  https://drive.google.com/file/d/1mfTkTlPFGxk90P1y4xr1VUBHQsN2UOXO/view?usp=sharing

**Comment by eneim** [comment]
@Kitlabs Can you send me the xml layout of your ViewHolder, and the Video URL that can reproduce this? via email is fine: nam@ene.im

**Comment by eneim** [comment]
@Kitlabs really bad your email is filtered to spam ... Check it now.

**Comment by Kitlabs** [comment]
Okay,thanx @eneim

**Comment by Kitlabs** [comment]
Hi @eneim ,Any Updates?

**Comment by eneim** [comment]
@Kitlabs not much. I cannot reproduce the issue on Oreo Pixel XL emulator. Is this 100% happen on your test?

**Comment by Kitlabs** [comment]
Yes @eneim, i have tested on one plus 3T (oreo),Motorola (oreo) ,Samsung(marshmallow),Redmi(Marshmallow),Sony(Lollipop) ,but the problem is only on oreo

**Comment by Kitlabs** [comment]
Hi @eneim I hope you'll be looking for the bug

**Comment by eneim** [comment]
Hey sorry for the lack of comment. Quite time issue. I can only use emulator to verify on Oreo and could not reproduce it yet. I will help create a demo so you can test on it. Maybe somewhere this weekend. (FYI living at UTC +9:00).

**Comment by Kitlabs** [comment]
yes Please @eneim try to help me out in any way you can,Thank you for the efforts you are doing

**Comment by Kitlabs** [comment]
@eneim i found a solution ,
The problem was with Surface_type of Exoplayer in xml .Firstly i was using surface_view but now i am using texture_view with hardwareAccelerated true in AndroidManifest.xml  it works :)

**Comment by Kitlabs** [comment]
The problem still exists with surface_view but still, Thanks for you Time,You can close this issue if you want to.

**Comment by eneim** [comment]
@Kitlabs Good to hear. Though SurfaceView is superior over TextureView, I highly recommend you to consider this. I acknowledge that changing to use TextureView may help to resolve the issue temporarily, so if it works for you, no problem.

I will keep this issue alive, and still think it would be nice if you can give more information about the issue like: when it happens and how often it happens. I doubt that the issue is so device-depend and I can escalate this to ExoPlayer dev team via their issue tracker to help solving this issue from root.

**Comment by Kitlabs** [comment]
@eneim The issue with SurfaceView is 100% ,i have tested on multiple oreo devices

**Comment by Kitlabs** [comment]
@eneim,The problem is solved with surface_view as well :) actually i was missing to make the hardwareAccelerated true in case of surface_view
So the thing is  android:hardwareAccelerated="true" must be there in AndroidManifest.xml for surface_view and texture_view

**Comment by Kitlabs** [comment]
Please make a note for this in your tutorial,if this is not mentioned Specifically

Thanks

**Comment by eneim** [comment]
@Kitlabs Thanks. I will take this into account. Having hardwareAccelerated to true will affect battery usage so it should be careful. It is good to know it works well for your app.

**Comment by anubhavmalik** [comment]
I have the same problem.. However, doing hardwareAccelerated = true doesn't solve my problem.

I'm looking into it further, in case any other solution is found. Could you discuss it here?

**Comment by eneim** [comment]
@anubhavmalik You should create a new issue and describe the behaviour a bit more. I would like to know your current behaviour and your expected behaviour. Also your device you are using for testing, Android version, Toro version, log cat/stack trace if it is available.

**Comment by anubhavmalik** [comment]
@eneim .. Sorry for replying late. Seems like my design was at fault and not the library. There was a part of the consecutive videos overlapping my current video and also while scrolling the player view seemed shaky.. 

However, it was because in I was having wrap content for height and match parent for width. So, my layout had to be drawn with wrap content at every point causing this issue. 

Now, I have started using a more reliable system by using aspect ratios and fixing sizes of my item in the recycler view. That fixed the problem.

Good library by the way man, thanks and cheers! :D
